### ISSUE TITLE
Accounts.ui.LoginForm without createContainer

### ISSUE THREAD

**Issue by gerwinbrunner** [studiointeract/accounts-ui#117]
Hi,
I just ran into a problem with the responsiveness of the LoginForm.
The default export of the component happens with the [createContainer](https://github.com/studiointeract/accounts-ui/blob/release-1.2.21/imports/ui/components/LoginForm.jsx#L1021).

But the Accounts.ui.LoginForm is just assigned the ['plain' component](https://github.com/studiointeract/accounts-ui/blob/release-1.2.21/imports/ui/components/LoginForm.jsx#L1019).

Is this intentional?
If so, be aware that it breaks the [Apollo starter kit](https://github.com/apollographql/meteor-starter-kit/blob/eecb42f5a175a42128dcc1e4a54a354f1c837c29/imports/ui/LoginForm.js#L16).

This should also be pointed out in the docs.

If this is not intended a fix could look like this.
To have the container wrapped in both cases, I created the following fix:
```
const LoginFormContainer = createContainer(() => {
  // Listen for the user to login/logout and the services list to the user.
  Meteor.subscribe('servicesList');
  return ({
    user: Accounts.user(),
  });
}, LoginForm);

Accounts.ui.LoginForm = LoginFormContainer;
export default LoginFormContainer;
```

**Comment by timbrandin** [comment]
Looks good, could you create a PR for the change?

**Comment by ianchanning** [comment]
@gerwinbrunner When you say 'breaks the Apollo starter kit', what do you mean? I'm experiencing some issues where I can't see the profile state of the form and I'm trying to figure out if this issue is connected.

With me it would appear that the internal `user` isn't set, so in the `LoginForm.jsx` on [line 321][1], you have the following:

```javascript
    if (user && formState == STATES.PROFILE) {
      loginButtons.push({
        id: 'signOut',
        label: this.translate('signOut'),
        disabled: waiting,
        onClick: this.signOut.bind(this)
      });
}
```

I can force the `STATES.PROFILE` by passing it in, but the `signOut` button never appears.
[1]: https://github.com/studiointeract/accounts-ui/blob/master/imports/ui/components/LoginForm.jsx#L321

**Comment by ianchanning** [comment]
This is what I'm seeing. There appears to be no `props.user`

![screenshot from 2017-08-01 11-13-51](https://user-images.githubusercontent.com/233318/28827547-355f969c-76ce-11e7-8822-7f4dff5a7fbf.png)

**Comment by Elviron** [comment]
Please open a new issue if this i still not resolved :) @ianchanning
