### ISSUE TITLE
is it possible that you are mixing client and server code

### ISSUE THREAD

**Issue by radzom** [studiointeract/accounts-ui#16]
Hi in the [meteor docs](http://docs.meteor.com/)

Accounts.ui.config is for client side
and 
Accounts.onCreateUser for server side

I do not understand how or why are you mixing them with the postSignUpHook and think this is the cause why my app broke after upgrading to accounts-ui 1.1.5
I get the error
```
W20160402-23:59:43.756(2)? (STDERR) Error: Can only call onCreateUser once
W20160402-23:59:43.772(2)? (STDERR)     at AccountsServer.onCreateUser (packages/accounts-base/accounts_server.js:120:13)
W20160402-23:59:43.772(2)? (STDERR)     at exports.default (server/configs/accounts_setup.js:5:12)
W20160402-23:59:43.772(2)? (STDERR)     at meteorInstall.server.main.js (server/main.js:6:1)
...
```

**Comment by timbrandin** [comment]
The onPostSignUpHook is meant to work both client side and server side, you may use it how you wish, the implementation is done so that this code only runs on the server and if you've implemented the hook. https://github.com/studiointeract/accounts-ui/blob/master/main_server.js#L6

But I see the issue here, accounts-ui is installed first, and it'd be better if we rather removed the hook.

**Comment by timbrandin** [comment]
https://github.com/studiointeract/accounts-ui/releases/tag/release-1.1.6
