### ISSUE TITLE
SocialButtons Don't Work?

### ISSUE THREAD

**Issue by VikR0001** [studiointeract/accounts-ui#47]
I see that LoginForm has a SocialButtons element. How do I enable it so as to make it visible on the LoginForm?

**Comment by VikR0001** [comment]
I've run `meteor add accounts-facebook` to see if that would be enough to get an initial Facebook login button to appear on the login page, but it does not yet appear. I'm sure it's something very obvious that I'm missing. What is the correct way to access social login buttons on the login page?

Thanks in advance for the info.

**Comment by jshimko** [comment]
I just ran `meteor add accounts-facebook` and the button showed up in my form.  No custom template.  Just a FlowRouter route like this...
```js
  FlowRouter.route('/login', {
    name: 'login',
    action() {
      mount(LoginLayout, {
        content: () => (<Accounts.ui.LoginForm />)
      });
    }
  });
```

**Comment by VikR0001** [comment]
That is exactly what I've done here. To test, I just re-ran `meteor add accounts-facebook` and coped and pasted the FlowRouter code you posted, only changing the variable `LoginLayout` to my variable name, `MainLayoutCtx`.  The Facebook button does not appear on my form. 

How are you configuring Accounts and Accounts.ui? Is it possible I need to update something there?

**Comment by jshimko** [comment]
Just some friendly advice on effective bug reporting and support requests...  

If your situation is dire (like "dead in the water for 3 days" as you stated in #48 ), I generally recommend spending the time to publish a simple example app reproducing your problem(s).  I find that developers are far more likely to help you solve your problems if you make it easy for them to see what you have going on.  Having to guess at what you've tried or what your code looks like usually makes helping a lot harder (which, in my experience, makes it a lot less likely to happen).

We're all busy and nobody's getting paid for open source support, so anything you can do to reduce the barriers to getting assistance is in your best interest.  [Meteor's bug reporting guidelines](https://github.com/meteor/meteor/blob/devel/Contributing.md#reporting-a-bug-in-meteor) are a perfect example of this.  

> A Meteor app has many moving parts, and it's often difficult to reproduce a bug based on just a few lines of code. So your report should include a reproduction recipe. By making it as easy as possible for others to reproduce your bug, you make it easier for your bug to be fixed. It's likely that without a reproduction, contributors won't look into fixing your issue and it will end up being closed.

See the section right below that on creating a reproduction.  Putting together a simple Meteor app with 1 or 2 files to demonstrate how something isn't working for you is, by far, the most effective way to get someone to look at your problem and potentially solve it.  Otherwise, people have to spend far more time writing back and forth to figure out what's happening in code they can't see.

So to use your specific issue as an example, a simple app showing your setup and how the social buttons don't appear could likely be produced in a single file with a few dozen lines of code.

**Comment by VikR0001** [comment]
Will do. Thanks.

**Comment by VikR0001** [comment]
Hmmm. Everything works fine in the tiny test app. I have no idea yet what my app could be doing differently from the tiny test app, that is interfering with accounts-ui. :) Maybe I'll find it.
