### ISSUE TITLE
BUG: Error «Need to set a username or email» when email is set

### ISSUE THREAD

**Issue by nadeemja** [studiointeract/accounts-ui#61]
Hello,

Using latest version as of now. 

**Steps to reproduce**:
1. _First_ fill out login form with both email and password,
2. _Then_ click register button.
3. _Finally_ click register button again.
4. _Observe_ error message.

Changing the already set email-field makes it work again. 
But this is no solution.

What to do? :)

**Comment by tr0lyat** [comment]
+1 Does anyone have a build that does not do this? Which version are you using? I am having this same issue with React Router and Semantic.

**Comment by plambe8** [comment]
Have this same issue. Pretty huge imo

**Comment by rogerdek** [comment]
I believe this is the same issue as described in #43 as well as in TelescopeJS/Telescope#1308

It seems that if you enter a password and then click "Register" the password field converts to an Email field (type=email) which will make the password visible.

**Comment by timbrandin** [comment]
This seems to be related to the email field being reset on state changes to formState. I'm thinking this could be solved while also adding a feature to remember previous entered values while switching between routes, states and also. Because as it is now it will forget the field state when switching routes, which I think was one of the best features of the original account-ui in Meteor.

**Comment by timbrandin** [comment]
This is solved in latest release.
